/cirtesub/analyzers:
  ros__parameters:
    path: CIRTESUB
    pub_rate: 1.0
    controllers:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Controllers
      startswith:
        - /Controllers
    navigation:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Navigation
      startswith:
        - /Navigation
    sensors:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Sensors
      startswith:
        - /Sensors
    hardware:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Hardware
      startswith:
        - /Hardware
    watchdog:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Watchdog
      startswith:
        - /Watchdog
        - Watchdog
        - /cirtesub/Watchdog
        - cirtesub/Watchdog
      contains:
        - Watchdog/Robot
